<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_pdfjs_reader_menu() {
  return array(
    'admin/islandora/pdfjs_reader' => array(
      'title' => 'pdf.js Reader',
      'description' => 'Configure the Mozilla pdf.js Reader.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_pdfjs_reader_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_pdfjs_reader_theme() {
  return array(
    'islandora_pdfjs_reader' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-pdfjs-reader',
      'variables' => array(
        'object' => NULL,
        'datastream_id' => 'OBJ',
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_pdfjs_reader_islandora_viewer_info() {
  return array(
    'islandora_pdfjs_reader' => array(
      'label' => t('pdf.js Reader'),
      'description' => t('Mozilla pdf.js Reader.'),
      'configuration' => 'admin/islandora/pdfjs_reader',
      'callback' => 'islandora_pdfjs_reader_viewer_callback',
      'model' => array('islandora:sp_pdf'),
      'mimetype' => array('application/pdf'),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_pdfjs_reader'.
 *
 * @return string
 *   HTML repersentation of the pdf.js Reader.
 */
function islandora_pdfjs_reader_viewer_callback(array $params) {
  return theme('islandora_pdfjs_reader', $params);
}
